# install nodejs and npm 
# - name: "Add nodejs apt key"
#   apt_key:
#     url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
#     state: present

# - name: "Add nodejs 13.x ppa for apt repo"
#   apt_repository:
#     repo: deb https://deb.nodesource.com/node_13.x bionic main
#     update_cache: yes
- name: "download nodejs 13.8"
  become: true
  shell: |
         curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash 
        #   ubuntu 18 
        #  - > out.out || exit 0 && exit 0 

- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present

#  install dependencies 
# install pm2 
- name: "Install NPM-distributed command-line tools"
  npm:
    global: yes
    name: "pm2"


